### PR TITLE
some update and bug fix

### PR DESCRIPTION
**Pull request by MickWang**
fix parameter error for makeTransactionByJson;
update axios version;
update bigInt serialize method, make the result 8 bytes; This  update is needed because the Ont app on ledger only recognize 8 bytes amount.

### CODE REVIEW

**Comment by WyattMufson** [comment]
@MickWang this PR breaks our system. We are verifying the tx payload built with the neovm-utils SDK (which uses the main golang protocol repo) with one built with the TS SDK. Now integer value parameters no longer match in size as of 1.0.17.

**Comment by MickWang** [comment]
@WyattMufson  We know the difference. This PR was to support the ONT app on Ledger, which can only recognize the value as 8 bytes.

**Comment by WyattMufson** [comment]
@MickWang any chance to make that a different parameter type? Like `LedgerInt` to support backwards compatibility? Ledger isn't the only one using this.

**Comment by MickWang** [comment]
Is this difference matters? It will need a lot of change in the ledger related apps if we add a new parameter type.

**Comment by WyattMufson** [comment]
It matters since you're changing the way transactions are built. A transaction made with the ts sdk won't match other sdks.

**Comment by MickWang** [comment]
But they both works on the nodes. Is it ok the transactions built with ts sdk does not match other sdks?

**Comment by WyattMufson** [comment]
You now can't use the ts sdk to verify transactions, so it can no longer be used for signing servers

**Comment by WyattMufson** [comment]
You could add another type that replicates the old functionality - and we can switch to that. That way ledger can stay the same.

**Comment by MickWang** [comment]
it's not easy to replicates the old functionality with just another type. Could you please make a pr about it ?

**Comment by WyattMufson** [comment]
Yeah I can make a PR. Shouldn't be too hard to implement, right?

**Comment by WyattMufson** [comment]
I've added numerous types the iOS sdk before without any trouble

**Comment by MickWang** [comment]
yes. But i think the less change , the better.

**Comment by WyattMufson** [comment]
I agree. I think a simple type `SafeInteger` which just uses the old `toHexstr` is all that's needed.

**Comment by MickWang** [comment]
OK. Please make a pr about it. Thanks.

**Comment by WyattMufson** [comment]
Will do

**Comment by WyattMufson** [comment]
@MickWang https://github.com/ontio/ontology-ts-sdk/pull/162

**Pull request merged**
